name: CI - test Karma


on:
    push:
      branches:
        - pruebas    # Ejecutar las pruebas en cualquier rama en cada push
    pull_request:
      branches:
        - master   # Ejecutar las pruebas antes de fusionar a master
  
    workflow_dispatch:
    
    # Permisos para GitHub Actions
permissions:
    contents: read


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Setup
        run: npm ci
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI