name: Run unit test Jasmine karma tests

on:
  push:
    branches:
      - pruebas
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Verifica la versión de Node.js adecuada

      - name: Install dependencies
        run: npm install

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 fonts-liberation libappindicator3-1 xdg-utils

      - name: Run unit tests
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
